#!/usr/bin/env python3
"""
Simple test for AI content labeling property.
"""
import re
from bs4 import BeautifulSoup

def test_ai_content_labeling_in_html():
    """Test that AI content is properly labeled in HTML."""
    
    # Sample HTML content that might be generated by the Flask app
    sample_html = """
    <div class="dashboard-content">
        <div class="ai-insight-panel">
            <div class="ai-content-label">🤖 محتوى مُولد بالذكاء الاصطناعي</div>
            <div class="insight-content">
                <h3>تحليل المخزون</h3>
                <p>تم تحليل البيانات باستخدام الذكاء الاصطناعي</p>
            </div>
        </div>
        
        <div class="regular-content">
            <h3>بيانات المخزون العادية</h3>
            <p>هذا محتوى عادي غير مُولد بالذكاء الاصطناعي</p>
        </div>
        
        <div class="ai-insight-panel">
            <div class="ai-content-label">AI Generated Content</div>
            <div class="forecast-content">
                <h3>Enhanced Forecast</h3>
                <p>This forecast was enhanced using AI analysis</p>
            </div>
        </div>
    </div>
    """
    
    # Parse HTML
    soup = BeautifulSoup(sample_html, 'html.parser')
    
    # Find AI content panels
    ai_panels = soup.find_all(class_='ai-insight-panel')
    ai_labels = soup.find_all(class_='ai-content-label')
    
    # Property: Any AI content panel should have a corresponding label
    assert len(ai_panels) == len(ai_labels), \
        f"Each AI panel should have a label. Panels: {len(ai_panels)}, Labels: {len(ai_labels)}"
    
    # Property: AI labels should indicate AI generation
    for label in ai_labels:
        label_text = label.get_text().strip()
        has_ai_indicator = any(keyword in label_text.lower() for keyword in [
            'ذكاء', 'اصطناعي', 'ai', 'generated', 'مُولد'
        ])
        assert has_ai_indicator, \
            f"AI label should indicate AI generation. Got: '{label_text}'"
    
    # Property: Regular content should not have AI labels
    regular_content = soup.find_all(class_='regular-content')
    for content in regular_content:
        # Should not contain AI content labels
        nested_labels = content.find_all(class_='ai-content-label')
        assert len(nested_labels) == 0, \
            "Regular content should not contain AI content labels"
    
    print("✅ AI content labeling test passed!")
    print(f"Found {len(ai_panels)} AI panels with {len(ai_labels)} labels")
    for i, label in enumerate(ai_labels):
        print(f"  Label {i+1}: {label.get_text().strip()}")
    
    return True

def test_ai_content_labeling_consistency():
    """Test that AI content labeling is consistent across different content types."""
    
    # Different types of AI content that might appear
    ai_content_samples = [
        {
            'type': 'insights',
            'html': '<div class="ai-insight-panel"><div class="ai-content-label">🤖 AI Insights</div><p>Stock analysis</p></div>'
        },
        {
            'type': 'forecast',
            'html': '<div class="ai-forecast-panel"><div class="ai-content-label">AI Generated Forecast</div><p>Demand prediction</p></div>'
        },
        {
            'type': 'report',
            'html': '<div class="ai-report-section"><div class="ai-content-label">تقرير ذكي</div><p>Smart report content</p></div>'
        }
    ]
    
    all_labels = []
    
    for sample in ai_content_samples:
        soup = BeautifulSoup(sample['html'], 'html.parser')
        labels = soup.find_all(class_='ai-content-label')
        all_labels.extend(labels)
    
    # Property: All AI content should have labels
    assert len(all_labels) == len(ai_content_samples), \
        "Each AI content sample should have exactly one label"
    
    # Property: All labels should indicate AI generation
    for label in all_labels:
        label_text = label.get_text().strip()
        has_ai_indicator = any(keyword in label_text.lower() for keyword in [
            'ai', 'ذكاء', 'اصطناعي', 'smart', 'ذكي', 'generated'
        ])
        assert has_ai_indicator, \
            f"All AI labels should indicate AI generation. Got: '{label_text}'"
    
    print("✅ AI content labeling consistency test passed!")
    print(f"Verified {len(all_labels)} AI content labels across different content types")
    
    return True

def test_ai_response_metadata_for_labeling():
    """Test that AI responses include metadata needed for proper labeling."""
    
    # Mock AI response structure
    ai_response = {
        'success': True,
        'data': {
            'insights': ['Stock levels are optimal', 'Reorder point reached for item X'],
            'recommendations': ['Increase safety stock', 'Review supplier performance']
        },
        'confidence_score': 0.85,
        'processing_time': 1.2,
        'cached': False,
        'ai_generated': True,
        'timestamp': '2024-01-01T12:00:00Z'
    }
    
    # Property: AI responses should include success indicator
    assert 'success' in ai_response, "AI response should include success indicator"
    
    # Property: Successful responses should include data
    if ai_response.get('success'):
        assert 'data' in ai_response, "Successful AI response should include data"
    
    # Property: Response should include metadata for UI labeling
    labeling_metadata = ['confidence_score', 'processing_time', 'cached', 'ai_generated', 'timestamp']
    has_metadata = any(key in ai_response for key in labeling_metadata)
    assert has_metadata, \
        f"AI response should include metadata for labeling. Available keys: {list(ai_response.keys())}"
    
    # Property: AI-generated flag should be present and True
    if 'ai_generated' in ai_response:
        assert ai_response['ai_generated'] is True, \
            "AI-generated content should be explicitly marked"
    
    print("✅ AI response metadata test passed!")
    print(f"Response includes metadata: {[key for key in labeling_metadata if key in ai_response]}")
    
    return True

if __name__ == "__main__":
    test_ai_content_labeling_in_html()
    test_ai_content_labeling_consistency()
    test_ai_response_metadata_for_labeling()
    print("\n🎉 All AI content labeling tests passed!")